version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  jupyter:
    image: jupyter/minimal-notebook
    restart: always
    # command:  /bin/bash -c "start.sh jupyter notebook --NotebookApp.token=''; pip install -r /home/jovyan/workspace/codes/requirements.txt"
    command: /bin/bash -c "start.sh jupyter notebook --NotebookApp.token=''"
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - ./workspace/:/home/jovyan/workspace
